version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - frontend
      - server

  frontend:
    image: ghcr.io/AgriReceipts/base-1-frontend:latest
    expose:
      - '5173'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - server

  server:
    image: ghcr.io/AgriReceipts/base-1-server:latest
    expose:
      - '3000'
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - '6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  caddy_data:
  caddy_config:
