# Production Configuration for EC2
version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    environment:
      - VITE_API_BASE_URL=http://13.127.162.248:3000/api/
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - '3000:3000'
    env_file:
      - server/.env.production
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://13.127.162.248
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
